- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Microsoft Azure(0cff93f3-2b71-4db6-80be-027c015a5df4)'
    appType: 'webAppLinux'
    WebAppName: 'SampleLinuxWebApp'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'